name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: DIOLINK/Diolink@main #PLEASE USE MAIN BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: 'False'
          SHOW_LINES_OF_CODE: 'True'
          SHOW_LOC_CHART: 'False'
          LOCALE: 'en'
